version: 0.2

phases:   
  install:
    runtime-versions:
      dotnet: 5.0
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Hiwell.AddressBook.sln
            
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Hiwell.AddressBook.sln
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false Hiwell.AddressBook.API/Hiwell.AddressBook.API.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./Hiwell.AddressBook.API/bin/Release/net5.0/linux-x64/publish/
  discard-paths: no