version: 0.2

phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
            
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false -o ./build-output ./Hiwell.AddressBook.API/Hiwell.AddressBook.API.csproj
      - cp Procfile ./build-output
artifacts:
  files:
    - '**/*'
  base-directory: ./build-output
  discard-paths: no